# Generated by Django 2.1.5 on 2019-01-21 12:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190121_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='modified_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 21, 12, 50, 4, 871560, tzinfo=utc)),
        ),
    ]
